# CircleCI config
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12
    working_directory: ~/ec-commitments
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
